In [74]:
import pandas as pd
import numpy as np
import re

In [75]:
df_grampa_unfiltered = pd.read_csv("./labeled_data/grampa_positives.csv")
df_grampa_unfiltered.shape

(51345, 13)

In [69]:
# Drop duplicates in unfiltered
df_grampa_unfiltered = df_grampa_unfiltered.drop_duplicates(subset=['sequence'])
df_grampa_unfiltered = df_grampa_unfiltered.reset_index()
df_grampa_unfiltered.shape

(6760, 14)

In [70]:
df_grampa_filtered = pd.read_csv("./labeled_data/July10th_FilteredGRAMPA.csv")
df_grampa_filtered.head()

                       sequence   MIC
0  AAAAAAAIKMLMDLVNERIMALNKKAKK  20.0
1                    AAGMGFFGAR  25.4
2                  AAHCIALRKGYK  30.0
3                    AAHCIQLGKR  30.0
4                    AAHCIVLHHN  30.0

In [71]:
# Find rows in unfiltered df whose sequences are in filtered df
sequences = df_grampa_filtered['sequence'].to_list()
df_grampa_unfiltered = df_grampa_unfiltered[df_grampa_unfiltered['sequence'].isin(sequences)]
df_grampa_unfiltered.to_csv(r'test.csv', index=None, sep=',', mode='w')

In [72]:
df_grampa_unfiltered.loc[df_grampa_unfiltered['has_cterminal_amidation'] == False]

,index,Unnamed: 0,bacterium,modifications,sequence,strain,unit,url_source,value,is_modified,has_unusual_modification,has_cterminal_amidation,datasource_has_modifications,database
78,352,352,S. typhimurium,[],RFRPPIRRPPIRPPFYPPFRPPIRPPIFPPIRPPFRPPLGPFP,LT2,uM,http://aps.unmc.edu/AP/database/query_output.p...,0.367526,False,False,False,True,APD
88,389,389,S. aureus,[],FLPLLAGLAANFLPKIFCKITRK,MTCC 9542,uM,http://aps.unmc.edu/AP/database/query_output.p...,0.686098,False,False,False,True,APD
111,479,479,E. faecium,[],GILGKLWEGVKSIF,NaN,uM,http://aps.unmc.edu/AP/database/query_output.p...,0.903090,False,False,False,True,APD
162,680,680,E. coli,[],SLLSLIRKLIT,ATCC 25922,uM,http://aps.unmc.edu/AP/database/query_output.p...,1.903090,False,False,False,True,APD
170,718,718,E. cloacae,[],KRFKKFFKKLKNSVKKRAKKFFKKPRVIGVSIPF,NaN,uM,http://aps.unmc.edu/AP/database/query_output.p...,-0.618588,False,False,False,True,APD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116,4458,9118,S. aureus,C-Terminal,FFPIVGKLLFGLSGLL,NaN,uM,http://split4.pmfst.hr/dadp/?a=kartica&id=SP_C...,-0.136677,True,True,False,True,DADP
1121,4475,9230,S. aureus,C-Terminal,GIGSLLAKAAKLGANLL,NaN,uM,http://split4.pmfst.hr/dadp/?a=kartica&id=SP_2958,1.096910,True,True,False,True,DADP
1954,10259,15906,S. saprophyticus,[],INLLKIAKGIIKSL,NaN,uM,https://dbaasp.org/peptide-card?id=2123,1.214971,False,False,False,True,DBAASP
5533,36529,45476,S. uberis,[],GLFGVLAKVAAHVVPAIAEHF,NaN,uM,https://dbaasp.org/peptide-card?id=5708,1.668263,False,False,False,True,DBAASP
5832,38641,47857,E. coli,[Unusual Acid],RRRWWW,DH5,uM,https://dbaasp.org/peptide-card?id=6238,0.954243,True,True,False,True,DBAASP

In [73]:
df_grampa_unfiltered.shape

(1737, 14)